# in order to be used correctly, the command 'wrapper' must be run
language: groovy
jdk:
 - oraclejdk7
branches:
 only:
 - master

before_script:
 - chmod +x grailsw

script: ./grailsw refresh-dependencies
 && ./grailsw "test-app"